### ISSUE TITLE
JavaScript link not working: injected base URL makes history API use cross-origin URLs

### ISSUE THREAD

**Issue by TheFoosh** [mozilla/thimble.webmaker.org#1052]
I tried to move a simple but working jQueryMobile app from the old Thimble to the new. It does not work in the new environment Preview mode(s), but works after Publishing. Instructions to reproduce the problem follow the link to a working example and the source code:

Link to working example
https://foosh.makes.org/thimble/LTE1OTQ0ODU3Ng==/made-with-thimble-and-jquerymobile
Source:
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Made with Thimble and jQueryMobile</title>
    <link rel="stylesheet" href="https://code.jquery.com/mobile/1.4.5/jquery.mobile-1.4.5.min.css" />
    <script src="https://code.jquery.com/jquery-1.11.1.min.js"></script>
    <script src="https://code.jquery.com/mobile/1.4.5/jquery.mobile-1.4.5.min.js"></script>
  </head>
  <body>

    <div  data-role="page" id="home">
      <div data-role="header">
        <h1>Home</h1>
      </div>
      <div data-role="content">
        
        <h2>Welcome</h2>
        <h3>This is the home page</h3>
        <ul data-role="listview">
          <li><a href="#page2">Next page</a></li>
        </ul>
        
      </div>
      <div data-role="footer" data-position="fixed">
        <h4>Footer content</h4>
        <div data-role="navbar">
        </div>
      </div>
    </div>

    <div  data-role="page" id="page2">
      <div data-role="header">
        <a href="#" class="ui-btn ui-icon-delete ui-btn-icon-left" data-rel="back">Back</a>
        <h1>Page 2</h1>
        <a href="#home" class="ui-btn ui-icon-home ui-btn-icon-left" data-transition="flip">Home</a>
      </div>
      <div data-role="content">
        
        <h2>Welcome</h2>
        <h3>This is the home page</h3>
        <ul data-role="listview">
          <li><a href="#page2" data-transition="pop">Next page</a></li>
        </ul>
        
      </div>
      <div data-role="footer" data-position="fixed">
        <h4>Footer content</h4>
        <div data-role="navbar">
        </div>
      </div>
    </div>

  </body>
</html>

Steps to reproduce:
1) Paste the above code into a "new project from scratch" on the new Thimble (replacing all the initial code).
2) Optionally, choose Preview in Mobile mode
3) Press the Next page button. A loader image appears and spins indefinitely. The "next page" never appears. 

Repeating the same steps on the older Thimble platform achieves desired results. Once page 2 appears, test further using Back and Home buttons.  

I then published the above code on the new system at 
https://d157rqmxrxj6ey.cloudfront.net/foosh/5072
Once published, it works as expected.

**Comment by jgmac1106** [comment]
My tech knowledge is very limited but I would run across many examples in
old Thimble that would not display in preview until I published. I think it
happened most often when animating CSS (I have no idea how to use jQuery).

**Comment by humphd** [comment]
This is a tricky one.  What's happening here is that jQuery Mobile is trying set navigation history for the preview page, which lives on a Blob URL, but we dynamically inject a `base` element to allow protocol-less URLs to work, making the URL they are pushing cross-origin, and a security violation.  On the console I see:

```
Uncaught SecurityError: Failed to execute 'replaceState' on 'History': A history state object with URL 'blob:/https%3A//mozillathimblelivepreview.net/c1046433-6a79-404e-ae99-b331d04ea57b' cannot be created in a document with origin 'https://mozillathimblelivepreview.net'.
```
Fixing this requires breaking support for protocol-less URLs, or fixing that in another way.

**Comment by humphd** [comment]
This is a documented problem on the jquery mobile site, it seems.  I was able to fix it by adding a small script just below your inclusion of jquery mobile in the `head`, like this:

```html
...
<script src="https://code.jquery.com/jquery-1.11.1.min.js"></script>
<script src="https://code.jquery.com/mobile/1.4.5/jquery.mobile-1.4.5.min.js"></script>
<script>
  // Disable pushState, see pushState in http://demos.jquerymobile.com/1.2.1/docs/pages/page-navmodel.html
  $.mobile.pushStateEnabled = false;
</script>
```

**Comment by humphd** [comment]
It's annoying but not something we can really fix.  Thanks for filing this, I wanted to make sure we didn't have a bug I could correct.  Let us know if you hit other issues.

**Comment by TheFoosh** [comment]
Sorry, still not working, Dave!  Tried on lunch hour, can't stick around now. Still works fine on old Thimble without 
```pushStateEnabled = false;
```
...are you sure it's jQM-side? Thanks for your impressive response time!

**Comment by humphd** [comment]
It's related to how we load the content, and how origin security works related to history pushState.  When you say it isn't working, you added this:

```html
<script>
  // Disable pushState, see pushState in http://demos.jquerymobile.com/1.2.1/docs/pages/page-navmodel.html
  $.mobile.pushStateEnabled = false;
</script>
```

And it does what?  Do you have a published link I can see?
